using Azure;
using Azure.Data.Tables;
using MyCloudProject.Common;
using System;
using System.Collections.Generic;
using System.Text;

namespace MyExperiment
{

    public class ExperimentResult : ITableEntity, IExperimentResult
    {
        // Constructor to initialize the PartitionKey and RowKey, which are essential for identifying table entities in Azure Tables.
        public ExperimentResult(string partitionKey, string rowKey)
        {
            this.PartitionKey = partitionKey;
            this.RowKey = rowKey;
        }

        // The partition key used to group related entities in the Azure Table.
        public string PartitionKey { get; set; }

        // The row key used to uniquely identify an entity within a partition.
        public string RowKey { get; set; }

        // The timestamp indicating when the entity was last modified.
        public DateTimeOffset? Timestamp { get; set; }

        // An ETag used for optimistic concurrency when updating the entity.
        public ETag ETag { get; set; }

        // Unique identifier for the experiment related to this result.
        public string ExperimentId { get; set; }

        // Name of the experiment.
        public string Name { get; set; }

        // A brief description of the experiment.
        public string Description { get; set; }

        // The UTC time when the experiment started.
        public DateTime? StartTimeUtc { get; set; }

        // The UTC time when the experiment ended.
        public DateTime? EndTimeUtc { get; set; }

        // The duration of the experiment in seconds.
        public long DurationSec { get; set; }

        // URL of the input file used in the experiment.
        public string InputFileUrl { get; set; }

        // Array of URLs pointing to the output files generated by the experiment.
        public string[] OutputFiles { get; set; }

        // The accuracy of the experiment's results.
        public double Accuracy { get; set; }

        // The duration of the experiment as a TimeSpan object.
        public TimeSpan Duration { get; set; }

        // URL of the main output file from the experiment.
        public string OutputFileUrl { get; set; }
    }
}
